/** Balance / seesaw comparison items. heavySide: 'left' | 'right' (that side goes down). */
export const MEASUREMENT_ITEMS = [
  {
    id: 'seesaw-girl-boy',
    types: ['heavier', 'mixed'],
    scene: 'seesaw',
    promptHeavier: 'Who is heavier?',
    promptLighter: 'Who is lighter?',
    left: { emoji: '👧', label: 'Girl' },
    right: { emoji: '👦', label: 'Boy' },
    heavySide: 'left',
  },
  {
    id: 'cow-chick',
    types: ['lighter', 'mixed'],
    scene: 'balance',
    promptHeavier: 'Which animal is heavier?',
    promptLighter: 'Which animal is lighter?',
    left: { emoji: '🐄', label: 'Cow' },
    right: { emoji: '🐥', label: 'Chick' },
    heavySide: 'left',
  },
  {
    id: 'car-feather',
    types: ['intro', 'mixed'],
    scene: 'balance',
    intro: true,
    left: { emoji: '🚗', label: 'Car', caption: 'heavy' },
    right: { emoji: '🪶', label: 'Feather', caption: 'light' },
    heavySide: 'left',
  },
  {
    id: 'presents-small-big',
    types: ['presents', 'mixed'],
    scene: 'balance',
    promptPresents: 'Tap the heaviest present, then the lightest.',
    left: { emoji: '🎁', label: 'Small present', sizeClass: 'measure-item--small' },
    right: { emoji: '🎁', label: 'Big present', sizeClass: 'measure-item--large' },
    heavySide: 'right',
  },
  {
    id: 'rock-balloon',
    types: ['heavier', 'mixed'],
    scene: 'balance',
    promptHeavier: 'Which is heavier?',
    promptLighter: 'Which is lighter?',
    left: { emoji: '🪨', label: 'Rock' },
    right: { emoji: '🎈', label: 'Balloon' },
    heavySide: 'left',
  },
  {
    id: 'elephant-mouse',
    types: ['lighter', 'mixed'],
    scene: 'balance',
    promptHeavier: 'Which animal is heavier?',
    promptLighter: 'Which animal is lighter?',
    left: { emoji: '🐘', label: 'Elephant' },
    right: { emoji: '🐭', label: 'Mouse' },
    heavySide: 'left',
  },
  {
    id: 'presents-tall-short',
    types: ['presents', 'mixed'],
    scene: 'balance',
    promptPresents: 'Tap the heaviest present, then the lightest.',
    left: { emoji: '🎁', label: 'Tall present', sizeClass: 'measure-item--large' },
    right: { emoji: '🎁', label: 'Short present', sizeClass: 'measure-item--small' },
    heavySide: 'left',
  },
  {
    id: 'dog-kitten',
    types: ['heavier', 'mixed'],
    scene: 'seesaw',
    promptHeavier: 'Who is heavier?',
    promptLighter: 'Who is lighter?',
    left: { emoji: '🐕', label: 'Dog' },
    right: { emoji: '🐱', label: 'Kitten' },
    heavySide: 'left',
  },
  {
    id: 'book-stack',
    types: ['lighter', 'mixed'],
    scene: 'balance',
    promptHeavier: 'Which is heavier?',
    promptLighter: 'Which is lighter?',
    left: { emoji: '📚', label: 'Thick book' },
    right: { emoji: '📖', label: 'Thin book' },
    heavySide: 'left',
  },
  {
    id: 'watermelon-apple',
    types: ['heavier', 'mixed'],
    scene: 'balance',
    promptHeavier: 'Which fruit is heavier?',
    promptLighter: 'Which fruit is lighter?',
    left: { emoji: '🍉', label: 'Watermelon' },
    right: { emoji: '🍎', label: 'Apple' },
    heavySide: 'left',
  },
];
