export const state = {
  theme: null,
  emoji: null,
  bgColor: null,
  questions: [],
  qIndex: 0,
  score: 0,
  selectedAnswer: null,
  crossedSet: new Set(),
  placedCount: 0,
  currentQ: null,
  blocked: false,
  maxAnswer: 9,
  soundOn: true,
  hintOn: false,
  stats: { addCorrect: 0, addTotal: 0, subCorrect: 0, subTotal: 0 },
  keyInputBuffer: '',
  keyInputTimer: null,
  addGroup1Count: 0,
  addGroup2Count: 0,
};
