export const prefersReducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;

export const els = {
  app: document.getElementById('app'),
  appNavHome: document.getElementById('app-nav-home'),
  appNavTitle: document.getElementById('app-nav-title'),
  appModal: document.getElementById('app-modal'),
  appModalBackdrop: document.getElementById('app-modal-backdrop'),
  appModalTitle: document.getElementById('app-modal-title'),
  appModalMessage: document.getElementById('app-modal-message'),
  appModalCancel: document.getElementById('app-modal-cancel'),
  appModalConfirm: document.getElementById('app-modal-confirm'),
  homeScreen: document.getElementById('home-screen'),
  mathSetupScreen: document.getElementById('math-setup-screen'),
  spellingSetupScreen: document.getElementById('spelling-setup-screen'),
  spellingPlayScreen: document.getElementById('spelling-play-screen'),
  phonicsPlayScreen: document.getElementById('phonics-play-screen'),
  arrowPlayScreen: document.getElementById('arrow-play-screen'),
  spellModePhonics: document.getElementById('spell-mode-phonics'),
  spellModePicture: document.getElementById('spell-mode-picture'),
  spellModeArrow: document.getElementById('spell-mode-arrow'),
  phonicsGrid: document.getElementById('phonics-grid'),
  phonicsPlayAzBtn: document.getElementById('phonics-play-az-btn'),
  phonicsSoundToggle: document.getElementById('phonics-sound-toggle'),
  spellingCatFieldset: document.getElementById('spelling-cat-fieldset'),
  spellingSetupHint: document.getElementById('spelling-setup-hint'),
  spellingStartBtn: document.getElementById('spelling-start-btn'),
  arrowQLabel: document.getElementById('arrow-q-label'),
  arrowProgressFill: document.getElementById('arrow-progress-fill'),
  arrowPrompt: document.getElementById('arrow-prompt'),
  arrowExample: document.getElementById('arrow-example'),
  arrowBoard: document.getElementById('arrow-board'),
  arrowBoardStage: document.getElementById('arrow-board-stage'),
  arrowPathsSvg: document.getElementById('arrow-paths-svg'),
  arrowBuilderSlots: document.getElementById('arrow-builder-slots'),
  arrowFoundList: document.getElementById('arrow-found-list'),
  arrowFeedback: document.getElementById('arrow-feedback'),
  arrowSubmitBtn: document.getElementById('arrow-submit-btn'),
  arrowSoundToggle: document.getElementById('arrow-sound-toggle'),
  arrowHearWordBtn: document.getElementById('arrow-hear-word-btn'),
  mainScreen: document.getElementById('main-screen'),
  endScreen: document.getElementById('end-screen'),
  pickMath: document.getElementById('pick-math'),
  pickSpelling: document.getElementById('pick-spelling'),
  spellCatCvc: document.getElementById('spell-cat-cvc'),
  spellCatBlend: document.getElementById('spell-cat-blend'),
  spellCatDigraph: document.getElementById('spell-cat-digraph'),
  spellCatMixed: document.getElementById('spell-cat-mixed'),
  spellingBackBtn: document.getElementById('spelling-back-btn'),
  spellingQLabel: document.getElementById('spelling-q-label'),
  spellingProgressFill: document.getElementById('spelling-progress-fill'),
  spellingPrompt: document.getElementById('spelling-prompt'),
  spellingEmoji: document.getElementById('spelling-emoji'),
  spellingSlotsRow: document.getElementById('spelling-slots-row'),
  spellingBank: document.getElementById('spelling-bank'),
  spellingFeedback: document.getElementById('spelling-feedback'),
  spellingSubmitBtn: document.getElementById('spelling-submit-btn'),
  spellingSoundToggle: document.getElementById('spelling-sound-toggle'),
  spellingHearWordBtn: document.getElementById('spelling-hear-word-btn'),
  mathBackBtn: document.getElementById('math-back-btn'),
  mathStartBtn: document.getElementById('math-start-btn'),
  modeMixed: document.getElementById('math-mode-mixed'),
  modeAdd: document.getElementById('math-mode-add'),
  modeSub: document.getElementById('math-mode-sub'),
  modeBeforeAfter: document.getElementById('math-mode-before-after'),
  modeBetween: document.getElementById('math-mode-between'),
  mathDisplay: document.getElementById('math-display'),
  mathArithmeticView: document.getElementById('math-arithmetic-view'),
  mathOrderView: document.getElementById('math-order-view'),
  mathOrderPrompt: document.getElementById('math-order-prompt'),
  mathOrderSequence: document.getElementById('math-order-sequence'),
  mathOrderBlank: document.getElementById('math-order-blank'),
  emojiZone: document.getElementById('emoji-zone'),
  diffEasy: document.getElementById('math-diff-easy'),
  diffMedium: document.getElementById('math-diff-medium'),
  diffHard: document.getElementById('math-diff-hard'),
  qLabel: document.getElementById('q-label'),
  progressFill: document.getElementById('progress-fill'),
  num1Val: document.getElementById('num1-val'),
  opSign: document.getElementById('op-sign'),
  num2Val: document.getElementById('num2-val'),
  mathBlank: document.getElementById('math-blank'),
  feedback: document.getElementById('feedback-msg'),
  numberPicker: document.getElementById('number-picker'),
  emojiContent: document.getElementById('emoji-content'),
  emojiZoneTitle: document.getElementById('emoji-zone-title'),
  subHint: document.getElementById('sub-hint'),
  submitBtn: document.getElementById('submit-btn'),
  soundToggle: document.getElementById('sound-toggle'),
  hintToggle: document.getElementById('hint-toggle'),
};

export function isTypingTarget(t) {
  return !!(
    t &&
    t instanceof HTMLElement &&
    (t.isContentEditable || /^(INPUT|TEXTAREA|SELECT)$/.test(t.tagName))
  );
}
